# Generated by Django 4.2 on 2026-03-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
