# Generated by Django 4.2 on 2026-03-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_parent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='clASS_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
