# Generated by Django 4.2 on 2026-03-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_parent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='face_image',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
