# Generated by Django 4.2 on 2026-03-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_student_face_image_student_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='clASS_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
