# Generated by Django 4.2 on 2026-03-24 14:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def backfill_student_admission_fields(apps, schema_editor):
    Student = apps.get_model("accounts", "Student")
    Classroom = apps.get_model("accounts", "Classroom")

    classroom_lookup = {
        classroom.name.lower(): classroom.id
        for classroom in Classroom.objects.all()
    }

    for student in Student.objects.select_related("user").all():
        full_name = f"{student.user.first_name} {student.user.last_name}".strip() or student.user.username
        updates = []

        if not student.full_name:
            student.full_name = full_name
            updates.append("full_name")

        if not student.admission_class_id and student.class_name:
            classroom_id = classroom_lookup.get(student.class_name.lower())
            if classroom_id:
                student.admission_class_id = classroom_id
                updates.append("admission_class")

        if updates:
            student.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_classroom_remove_teacher_class_name_teacher_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to='accounts.classroom'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_date', 'class_name'], name='accounts_st_admissi_e209d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('roll_number', 'class_name'), name='unique_student_roll_number_per_class'),
        ),
        migrations.RunPython(backfill_student_admission_fields, migrations.RunPython.noop),
    ]
