# Generated by Django 4.2 on 2026-04-07 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_student_admission_class_student_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='attendance_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_classes', to='accounts.teacher'),
        ),
    ]
