# Generated by Django 5.2.11 on 2026-03-04 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_face_image'),
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='assigned_date',
            new_name='date_assigned',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
        migrations.AddField(
            model_name='homework',
            name='class_name',
            field=models.CharField(default='Class 10', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homework_files/'),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
            preserve_default=False,
        ),
    ]
