# Generated by Django 5.2.11 on 2026-03-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_rename_assigned_date_homework_date_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='homework',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
    ]
