# Generated by Django 5.2.11 on 2026-03-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_classroom_remove_teacher_class_name_teacher_classes'),
        ('homework', '0003_remove_homework_due_date_remove_homework_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='accounts.teacher'),
        ),
    ]
