# Generated by Django 5.2.11 on 2026-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_classroomcamera'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unknown_faces/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
