# Generated by Django 4.2.29 on 2026-03-12 23:53

from django.db import migrations, models
import django.utils.timezone


def backfill_attendance_fields(apps, schema_editor):
    Attendance = apps.get_model("attendance", "Attendance")

    for row in Attendance.objects.select_related("student").all().iterator():
        changed_fields = []

        if not row.student_class:
            row.student_class = getattr(row.student, "class_name", "") or ""
            changed_fields.append("student_class")

        if row.created_at is None:
            row.created_at = row.marked_at or django.utils.timezone.now()
            changed_fields.append("created_at")

        if changed_fields:
            row.save(update_fields=changed_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_marked_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_class',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.RunPython(backfill_attendance_fields, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='attendance__date_3889e6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'student_class'], name='attendance__date_3f789a_idx'),
        ),
    ]
