# Generated by Django 4.2 on 2026-04-07 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_classroom_attendance_teacher'),
        ('attendance', '0009_attendance_created_at_attendance_student_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marks', to='accounts.teacher'),
        ),
    ]
